[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs" 